# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install robotframework robotframework-seleniumlibrary && wget https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && rm chromedriver_linux64.zip && sudo mv chromedriver /usr/local/bin && sudo chmod +x /usr/local/bin/chromedriver
            
    displayName: 'Install dependencies'
  
  - powershell: robot --pythonpath . -x outputxunit.xml TestCases.robot
    displayName: 'Run Robot Scripts'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: outputxunit.xml
      searchFolder: 'D:\a\1\s\'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results outputxunit.xml'